### ISSUE TITLE
Gaps Count Towards Window Size?

### ISSUE THREAD

**Issue by danieldugas** [Airblader/i3#396] opened 2021-04-28 09:03 UTC
## I'm submitting a…

<pre>
[ ] Bug
[ ] Feature Request
[ ] Documentation Request
[x] Other (Please describe in detail)
</pre>

I'm not sure whether this is a bug or intended behavior

## Current Behavior
With large gaps, windows do not get tiled with equal size because gaps count towards window size:
![Screenshot from 2021-04-28 10-57-51](https://user-images.githubusercontent.com/1926730/116376577-b1270680-a810-11eb-97b0-398f486926d3.png)

## Expected Behavior
I would expect windows to get tiled with equal size despite gaps 

## Reproduction Instructions
```
bindsym $mod+g gaps horizontal all toggle 864, gaps vertical all toggle 432
```
open 3 windows

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: v4.19.2
</pre>

<details><summary>Config file</summary><pre>
</pre>
```
[default config with these lines added:]
# Specify the distance between windows in pixels. (i3-gaps)
gaps inner 10
gaps horizontal 864
gaps vertical 432
# gaps outer 0
# small mode for the big screen
bindsym $mod+g gaps horizontal all toggle 864, gaps vertical all toggle 432
```
</details>

<pre>
- Linux Distribution & Version: Ubuntu 18
- Are you using a compositor (e.g., xcompmgr or compton): yes
</pre>

**Comment by Airblader** [comment] 2021-04-28 09:05
Thanks for posting! This is a duplicate of #22.

**Closed as completed by Airblader** 2021-04-28 09:05 UTC

**Comment by orestisfl** [comment] 2021-04-28 10:56
If this is an actual issue, shouldn't we keep it around so that it can get accounted for https://github.com/i3/i3/issues/3724?

**Comment by Airblader** [comment] 2021-04-28 11:13
Gaps would have to be entirely reimplemented from scratch to work differently anyway, so I view this as an artifact of how i3-gaps works. If such an implementation were to produce the same effect, we'd notice it, I think.
