### ISSUE TITLE
i3-gaps has often overloads my CPU up to 100%

### ISSUE THREAD

**Issue by goodmind** [Airblader/i3#56] opened 2015-08-25 10:45 UTC
Hello,

`i3-gaps` has often overloads my CPU up to 100%.

My CPU is `Intel(R) Core(TM)2 Quad CPU Q8300`.

I don't understand why.

http://logs.i3wm.org/logs/5740874747084800.bz2
/var/run/user/1000/i3/errorlog.19732 contents:

```
ERROR: Received ConfigureNotify for unknown window 0x01000000
ERROR: Received ExposeEvent for unknown window 0x01000000
ERROR: Received ConfigureNotify for unknown window 0x01000000
ERROR: Received ConfigureNotify for unknown window 0x01000003
ERROR: Received ExposeEvent for unknown window 0x01000003
ERROR: Received ConfigureNotify for unknown window 0x01000003
ERROR: Received ConfigureNotify for unknown window 0x01000006
ERROR: Received ExposeEvent for unknown window 0x01000006
ERROR: Received ConfigureNotify for unknown window 0x01000006
ERROR: Received ConfigureNotify for unknown window 0x01000009
ERROR: Received ConfigureNotify for unknown window 0x01000009
ERROR: Received ConfigureNotify for unknown window 0x0100000c
ERROR: Received ConfigureNotify for unknown window 0x0100000c
ERROR: Received ConfigureNotify for unknown window 0x01000003
ERROR: Received ExposeEvent for unknown window 0x01000003
ERROR: Received ConfigureNotify for unknown window 0x01000003
ERROR: Received ConfigureNotify for unknown window 0x01000000
ERROR: Received ExposeEvent for unknown window 0x01000000
ERROR: Received ConfigureNotify for unknown window 0x01000000
ERROR: Received ConfigureNotify for unknown window 0x01000006
ERROR: Received ExposeEvent for unknown window 0x01000006
ERROR: Received ConfigureNotify for unknown window 0x01000006
```

My `i3-gaps` version is:

```
Binary i3 version:  4.10.3-347-g586854b (2015-07-30, branch "makepkg") © 2009-2014 Michael Stapelberg and contributors
Running i3 version: 4.10.3-347-g586854b (2015-07-30, branch "makepkg") (pid 19732)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3-with-/i3
```

**Comment by Airblader** [comment] 2015-08-25 10:49
Are you running some SDL app or Spotify? They are known to have problems in combination with i3, see https://github.com/i3/i3/issues/1124 and https://github.com/i3/i3/issues/1413.

One thing you can also do is run `xwininfo -all -id $ID` and `xprop -id $ID` where `$ID` is the "unknown window" from the log, but of course you need to do that right at the time where you experience the issue. This will at least reveal which window is causing this.

I really really doubt this is an i3-gaps issue, but I'll wait for your feedback before closing.

**Comment by goodmind** [comment] 2015-08-25 11:10
Yes, I have use `mpd` which depends on `ffmpeg` which depends on `sdl` but it hasn't any windows

**Comment by Airblader** [comment] 2015-08-25 11:14
Can you correlate this problem coming up with mpd running? In other words, does it ever happen when mpd isn't running?

Also, please do the steps I've outlined above to figure out the window that is going crazy here.

**Comment by goodmind** [comment] 2015-08-25 11:15
`xprop` and `xwininfo` says that there isn't window (`BadWindow (Invalid window parameter)`)

**Comment by Airblader** [comment] 2015-08-25 11:20
> Yes, I have use mpd which depends on ffmpeg which depends on sdl but it hasn't any windows

Yeah, I understood that. I'm asking whether you can correlate the CPU load with the fact that mpd is running. Does the CPU load ever increase like that even if mpd isn't running or does it only happen when you have mpd running?

> xprop and xwininfo says that there isn't window (BadWindow (Invalid window parameter))

Did you run these commands _while_ the CPU load was high? You really need to make sure that you run these commands on a window id that you see in the logs in the very moment it is being logged, not later on.

**Comment by goodmind** [comment] 2015-08-25 11:21
Yes, I run this while CPU was high

**Comment by Airblader** [comment] 2015-08-25 11:24
What about the first question? Does the problem occur if mpd isn't running?

The logs are pretty clear – i3 is being spammed with events. That's not an i3 problem, certainly not i3-gaps. I suggest the following:
- See if the problem still occurs if mpd isn't running (mentioned above).
- Install normal i3 (without gaps) and see if the problem occurs. If yes, this should be reported agains i3, not i3-gaps (though it likely isn't an i3 issue at all).

**Comment by goodmind** [comment] 2015-08-25 11:25
I have kill mpd, but i3 still high cpu, I can't restart without killing it and relogin

**Comment by Airblader** [comment] 2015-08-25 11:26
Yeah, please start a new session where mpd isn't running to see if this issue comes back up. If it does, please try to not run any programs at all. The most important thing is to figure out which application causes this.

**Comment by goodmind** [comment] 2015-08-25 11:29
I will try it without `mpd` soon

**Comment by goodmind** [comment] 2015-08-25 11:34
But, why `sdl` makes `i3` load CPU up to 100%

**Comment by Airblader** [comment] 2015-08-25 11:43
Actually, this isn't i3 being spammed. It's just a few of those errors during restart, which is fine. In the logs I can't see anything that is immediately problematic.

Please install vanilla i3 and reproduce the problem there. Then open an issue against i3 itself. I really can't imagine this being a problem of this fork.

I'll close the issue here due to that reason. If it turns out that it works fine with i3, but is only a problem with i3-gaps (which I don't expect to happen), let me know and we will reopen it.

**Closed as completed by Airblader** 2015-08-25 11:43 UTC
