### ISSUE TITLE
Artifacts when closing certain windows.

### ISSUE THREAD

**Issue by ReductoAdAbsurdum** [Airblader/i3#325] opened 2019-11-13 15:27 UTC
## I'm submitting a…
[x] Bug

## Current Behavior
Artifacts/graphical glitches behind certain windows when closing them:

(a) When I open either two Geany or Gvim windows and then close them, I get the artifacts...
(b) When I open only ONE window that is either Geany or Gvim and then close them...I do NOT get 
     the artifacts...
(c) When I open one or many urxvt windows and close them, again I do NOT get the artifacts..
     what could be wrong here ? does it have something to do with gtk apps ?
(d) This happens with or without Compton running...
## Expected Behavior
No artifacts

## Reproduction Instructions
open multiple instances of the Geany text editor and close all of them quickly...you would see the artifacts

## Environment
Binary i3 version:  4.17.1 (2019-08-30) © 2009 Michael Stapelberg and contributors
(Getting version from running i3, press ctrl-c to abort…)
Running i3 version: 4.17.1 (2019-08-30) (pid 5173)
Loaded i3 config: /home/legion/.config/i3/config (Last modified: Tue 12 Nov 2019 10:05:43 PM EST, 43820 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
i3 version: 4.17.1

## i3 config:
https://pastebin.com/pxUcXuMG

- Linux Distribution & Version: Void Linux
- Are you using a compositor (e.g., xcompmgr or compton): Compton

**Comment by ReductoAdAbsurdum** [comment] 2019-11-18 23:49
I kind of resolved this by swtiching to the intel modesetting driver... look here:
https://www.reddit.com/r/voidlinux/comments/dxuw4m/how_do_i_change_from_xf86videointel_to_the/

**Comment by Airblader** [comment] 2019-11-24 09:12
This seems like a compositing / graphics issue and has been resolved. Since there's nothing specific about i3-gaps mentioned here I'll close this. If you'd like to pursue the issue anyway please reproduce on i3 and open the issue upstream. If it cannot be reproduced there we can reopen this one. Thanks!

**Closed as completed by Airblader** 2019-11-24 09:12 UTC
