### ISSUE TITLE
Shift key modifier issue

### ISSUE THREAD

**Issue by jeefberkey** [Airblader/i3#96] opened 2016-08-09 13:06 UTC
Output of `i3 --moreversion 2>&- || i3 --version`:

```
Binary i3 version:  4.12-109-ge4fd3aa (2016-08-01, branch "4.12-109-ge4fd3aa") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.12-109-ge4fd3aa (2016-08-01, branch "4.12-109-ge4fd3aa") (pid 3788)
Loaded i3 config: /home/nick/.config/i3/config (Last modified: Tue 09 Aug 2016 08:26:20 AM EDT, 1708 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
```

URL to a logfile as per http://i3wm.org/docs/debugging.html:

http://logs.i3wm.org/logs/5764878782431232.bz2
and my config: http://pastebin.com/hiXKzeNB

**What I did:**

Pressing any of my key combinations that include a shift key modifer.
For example, I have this line in my config file:

```
bindsym $mod+Shift+f exec nautilus
```

**What I saw:**

i3 doesn't capture the shift key. If I press the key combo at a terminal it just prints a capital F. 

**What I expected instead:**

Nautilus to start. 

**More details:**

This is happening with every shift key modifier in my config, and only started happening the last time I updated `gaps-next`, so within the last week or two. I have gone back to `e4fd3aa` in the meantime. 

Thank you for your time.

**Comment by Airblader** [comment] 2016-08-09 18:35
Please report bugs not related to i3-gaps features upstream. However, in your particular case, I'm pretty confident this is a duplicate of https://github.com/i3/i3/issues/2417

**Closed as completed by Airblader** 2016-08-09 18:35 UTC

**Comment by jeefberkey** [comment] 2016-08-09 18:51
I will go +1 that bug. Thanks for correcting me.

**Comment by nullbio** [comment] 2016-09-12 07:56
This is affecting me as well. Also I have a mode set up that does shutdown/lock/restart etc, and in that mode none of the binds defined as `bindsym x` (where `x` is any lowercase letter) work, neither does `bindsym Escape`. If I put `bindsym $mod+Shift+R` I can use that to close it, so it is actually executing things inside the block, but for some reason those binds don't work.

I also noticed that if you define your shift key binds like so:

`$mod+Shift+R` instead of `$mod+Shift+r` it works. It seems using lowercase letters breaks it.
