### ISSUE TITLE
gaps between windows disappears when opening a stacked window twice

### ISSUE THREAD

**Issue by nhooyr** [Airblader/i3#138] opened 2017-03-15 20:44 UTC
Output of `i3 --moreversion 2>&- || i3 --version`:

```
Binary i3 version:  4.13-114-gd89d549 (2017-03-10, branch "gaps-next") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.13-114-gd89d549 (2017-03-10, branch "gaps-next") (pid 1174)
Loaded i3 config: /home/nhooyr/.config/i3/config (Last modified: Tue 14 Mar 2017 11:17:40 AM EDT, 104083 seconds ago)

The i3 binary you just called: /home/nhooyr/code/i3-gaps/build/i3
The i3 binary you are running: /home/nhooyr/code/i3-gaps/build/i3
```

URL to a logfile as per http://i3wm.org/docs/debugging.html:

http://logs.i3wm.org/logs/5749716474134528.bz2

**What I did:**

I booted my computer. I pressed `$mod+enter` to open a terminal and then I enabled logging with i3-msg. I pressed `$mod+s` to enable stacked windows. Then I pressed `$mod+enter` twice. Then I closed both windows with `ctrl+d` and finally, I pressed `$mod+h` and then `$mod+enter` to open a vertical terminal.

**What I saw:**

http://i.imgur.com/NBqs93O.png

The above screenshot has chrome on one side but imagine that was a terminal instead.

**What I expected instead:**
A gap between the two terminal windows.

**Comment by nhooyr** [comment] 2017-03-15 21:51
The gaps reappear if I close every window and then open two new windows.

**Comment by gerardbm** [comment] 2017-03-16 12:24
I also can reproduce it: open a new terminal (`$mod+Enter`), change layout to stacking (`$mod+s`), change split direction to horizontal/vertical (`$mod+h`) and open a second terminal (`$mod+Enter`).

Example: http://i.imgur.com/UD58Ezh.png

I'm not sure if it's the normal behaviour of splits into the stacking layout or if it's a bug to be solved.

**Comment by Airblader** [comment] 2017-03-16 12:26
What @gerardbm describes is intended behavior. I have to verify whether @nhooyr's situation leads to a similar container layout and is therefore just the same thing,.

**Comment by catvec** [comment] 2018-09-11 21:25
I can reproduce this issue by completing the following steps:

1. Open 2 windows in split mode
2. Selecting the parent of these 2 windows
3. Switch to stacked mode

This will cause the gap between the 2 windows to disappear:

![no-middle-gap](https://user-images.githubusercontent.com/3323504/45388091-f5c0ed80-b5e5-11e8-9c45-584f4664bdc5.png)

The way to fix this is to complete the following steps:

1. Select the parent of these 2 windows
2. Switch to split mode

This will cause the gap between the 2 windows to show again:

![with-middle-gap](https://user-images.githubusercontent.com/3323504/45388127-15581600-b5e6-11e8-8fac-0f9966645ce3.png)

This problem occurs when you select the parent of the 2 windows and switch to stacked mode. Instead you should select one of the windows and switch to stacked mode. I make this mistake commonly but it is a fairly easy fix.

**Comment by Airblader** [comment] 2018-11-03 20:03
Closing now as it seems like this is just a case of the intended behavior.

**Closed as completed by Airblader** 2018-11-03 20:03 UTC
