### ISSUE TITLE
Workspace gap setting doesn't work when using Font Awesome in its name

### ISSUE THREAD

**Issue by bootzin** [Airblader/i3#149] opened 2017-06-06 05:04 UTC
Output of `i3 --moreversion 2>&- || i3 --version`:

Binary i3 version:  4.13-158-gf0e6dcbf (2017-05-23, branch "gaps-next") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.13-158-gf0e6dcbf (2017-05-23, branch "gaps-next") (pid 806)
Loaded i3 config: /home/lincolnkonig/.config/i3/config (Last modified: Tue 06 Jun 2017 01:33:41 AM -03, 1299 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

**What I did:**
I've set my default gaps as inner 5 (no outer), then I tried to set my browser workspace (named 2:) gaps to 0, but no matter what I tried (with and without quotes and using the number) it continued to use the default value. I believe this is due to the fact that I use Font Awesome, because using the command to set another workspace (named simply "4:") as 0 worked just fine

**What I saw:**

The gaps were set to the default value instead of the custom workspace value

**What I expected instead:**
gaps should have been set to 0 in that specific workspace

**Comment by Airblader** [comment] 2017-06-06 07:34
I cannot reproduce this. Can you pastebin your config?

**Comment by bootzin** [comment] 2017-06-07 21:12
I actually noticed that rebooting the system (instead of simply restarting i3 in place) solved the issue.

**Comment by Airblader** [comment] 2017-06-08 07:55
It could be that the gaps calculation isn't done correctly in a restart scenario. I think I've seen that before.

**Comment by Airblader** [comment] 2018-11-03 20:02
Closing for now.

**Closed as completed by Airblader** 2018-11-03 20:02 UTC
Labels: bug
