### ISSUE TITLE
Right click menu (in chrome) not showing until mutliple windows in the container. 

### ISSUE THREAD

**Issue by Delvien** [Airblader/i3#176] opened 2017-11-14 14:47 UTC
i3-gaps latest version

Seems to only happen in chrome and randomly at that.

Smart-gaps is on.

Right clicking in chrome the context menu does not appear until multiple windows are opened up in the container. 

I havent pin-pointed how to reproduce this, but it only happens when there is only 1 window.

**Comment by Airblader** [comment] 2017-11-14 14:52
> i3-gaps latest version

That's not a useful information because people have vastly different thoughts on what that means (latest released? latest git? latest on your distro?)

Please try to reproduce this on vanilla i3 and let me know whether this appears there as well.

**Comment by Delvien** [comment] 2017-11-14 15:18
i3 --moreversion 2
Binary i3 version:  4.14.1-168-g5533e520 (2017-10-25, branch "gaps-next") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.14.1-168-g5533e520 (2017-10-25, branch "gaps-next") (pid 1574)
Loaded i3 config: /home/dm/.i3/config (Last modified: Tue 14 Nov 2017 09:38:42 AM EST, 2389 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: /usr/bin/i3


I compiled it from git, latest version here, using your instructions.

**Comment by Delvien** [comment] 2017-11-14 15:40
able to reproduce in vanilla i3. Going to report the bug there.

**Comment by Airblader** [comment] 2017-11-14 15:46
Thanks! That was the intention of reproducing it there. Closing here for obvious reasons.

**Closed as completed by Airblader** 2017-11-14 15:46 UTC
