### ISSUE TITLE
Fails to compile

### ISSUE THREAD

**Issue by ghost** [Airblader/i3#102] opened 2016-10-08 23:55 UTC
After cloning cloning and runing make as per the install instructions, I am greeted with the following compiler error:

[libi3] CC libi3/format_placeholders.c
In file included from libi3/format_placeholders.c:12:0:
inclide/libi3.h:21:25: fatal error: pango/pango.h: No such file or directory
 #include <pango/pango.h>
                         ^
compilation terminated

**Comment by Airblader** [comment] 2016-10-08 23:56
You haven't installed the required dependencies, in this case pango.

**Comment by Airblader** [comment] 2016-10-08 23:56
Also note that you should only compile yourself if necessary. Most distros have a package for i3-gaps by now.

**Comment by ghost** [comment] 2016-10-09 00:08
As far as I can tell, and according to my package manager pango is installed (version 1.40.3-1). For good measure I removed pango and installed it once more and the issue persists.

**Comment by Airblader** [comment] 2016-10-09 00:10
What distro are you on? Can you install regular i3 from the repositories?

Also, did you actually copy-paste that output above or retype it? I'm asking because it says »incl_i_de«

**Comment by ghost** [comment] 2016-10-09 00:12
I am on arch, I can install and use regular i3, and I retyped it. Sorry that's definately a typo. I get the same issue with i3-gaps on the aur.

**Comment by Airblader** [comment] 2016-10-09 00:16
What about vanilla i3 – does that build? What does `pkg-config --cflags pango` output? Does `/usr/include/pango-1.0/pango/pango.h` exist?

**Comment by Airblader** [comment] 2016-10-09 00:20
Just to be clear, when I say

> What about vanilla i3 – does that build?

I don't mean whether you can install the vanilla i3 package but whether you can compile it from source.

**Comment by ghost** [comment] 2016-10-09 00:33
Vanilla i3 doesn't build, it give me the following:
`/home/milo/builds/i3/common.mk:151: *** "cairo >= 1.14.4 missing".  Stop.`

However, my package manager is showing cairo 1.14.6-2 to be installed. As with pango I removed it and reinstalled for good measure.

`pkg-config --cflags pango` gives:
-I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include

/usr/include/pango-1.0/pango/pango.h exists

**Comment by Airblader** [comment] 2016-10-09 00:45
What does

```
pkg-config --modversion cairo
```

print? I suspect it'll tell you that your cairo version is, in fact, less than 1.14.4. It sounds to me like your system is in an inconsistent state.

**Comment by ghost** [comment] 2016-10-09 00:53
It gives 1.14.6

I see no reason why I might have an older verion, as this machine was only set up yesterday.

**Comment by Airblader** [comment] 2016-10-09 00:55
> It gives 1.14.6

Well now I'm starting to run out of ideas. Let's do the check just like i3 does it. What does

```
pkg-config --atleast-version=1.14.4 cairo ; echo $?
```

print?

**Comment by ghost** [comment] 2016-10-09 00:56
It prints `1`

**Comment by Airblader** [comment] 2016-10-09 01:06
None of this makes sense to me anymore. `pkg-config` tells you cairo == 1.14.6, but when it compares it against 1.14.4 it reports that your version isn't recent enough. Note that we're not even doing anything with i3 here, this is just an issue with base-devel at this point.

I don't think it makes much sense to investigate the original error until this is sorted out because right now I don't really trust your build environment. Can you address this issue on the Arch forums / mailing list or any other general Linux support you prefer, please? I currently wouldn't know how to investigate this further.

**Comment by ghost** [comment] 2016-10-09 01:17
OK, will do. Thanks for the input so far.

**Comment by Airblader** [comment] 2016-10-09 01:19
Sure thing. If you post in a forum please also post the link here so I can track the issue as well.

**Comment by hubbcaps** [comment] 2016-10-20 22:01
I'm experiencing this now as well on a fresh arch install. Same as @milolim, pkg config outputs correct version and returns 1 on a run of `pkg-config --atleast-version=1.14.4 cairo ; echo $?`

I can't find any thread opened on the Arch forums regarding this, I'll open one up though when I get off work and link back. It's just very weird that this check if failing when the version is clearly correct.

**Comment by hubbcaps** [comment] 2016-10-20 23:11
I've submitted a bug report with the pkg-config maintainers as this seems to me to be a pkg-config issue with the returning 1 falsely and causing the build to fail and exit

https://bugs.freedesktop.org/show_bug.cgi?id=98364

**Comment by Airblader** [comment] 2016-10-21 05:07
Thank you!

**Comment by ghost** [comment] 2016-10-21 15:29
I am getting this same issue but on fedora

**Comment by Airblader** [comment] 2016-10-21 15:29
Please don't keep posting here. The issue is upstream, you should raise that you're affect there so that the issue is resolved faster. Thanks!

**Comment by hubbcaps** [comment] 2016-10-21 21:16
@FireAntJoe Please go leave a comment on the freedesktop bug I raised. You'll need to create an account but it'll be worth showing I'm not the only one and the devs can actually fix it.

**Comment by Airblader** [comment] 2016-10-22 11:41
Can you confirm whether doing the check as suggested upstream works for you? If so I can push out a fix in i3-gaps for this. 4.13 will probably be released soon anyway and most likely will contain the open PR to exchange the build system with autotools anyway, so I assume at least for i3 the problem would disappear then.

**Comment by hubbcaps** [comment] 2016-10-22 17:45
Just got on and tested. 

Looking through the debug commands the Upstream dev gave I see it can't find the package "egl.pc". After some searching, I found this to be a component given by Mesa. Reinstalling the Mesa package and dependencies seems to have given me the required file. This should be good now.

I would however suggest implementing the devs pkg-config exists line as it's the current "Standard" check.

Thanks for your help on this @Airblader. @FireAntJoe and @milolim give this a shot, hopefully it clears it for you as well.

**Comment by Airblader** [comment] 2016-10-22 21:41
> I would however suggest implementing the devs pkg-config exists line as it's the current "Standard" check.

Given that with 4.13 we replace the entire build system anyway I think there's no point in doing this now that we know that it's not a problem in i3 or pkg-config. :-)

I'll close this issue for now. Thanks!

**Closed as completed by Airblader** 2016-10-22 21:41 UTC
Labels: waiting, support

**Comment by dbnicholson** [comment] 2016-10-24 03:59
@Airblader one suggestion I have - run the commands with `--print-errors` passed to pkg-config. Then it will be a lot more obvious to users (and you) where things are breaking down.

**Comment by ghost** [comment] 2016-10-25 18:25
I did both upstream and the other neither worked.

**Comment by Airblader** [comment] 2016-10-25 18:39
@FireAntJoe As of today the development branch (gaps-next) uses autotools, so this is pretty much obsolete anyway. You should try to compile that branch (using autotools).
