### ISSUE TITLE
i3 rendering full screen application (Dota 2) incorrectly, with vertical offset

### ISSUE THREAD

**Issue by BenQuigley** [Airblader/i3#338] opened 2020-02-03 17:40 UTC
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

Dota 2 is a game that runs on Ubuntu and opens in full screen. I believe that opening this game in i3 has worked normally in the past. However, when launching it in i3 (and after switching workspaces once), the current behavior is:

* The bottom of the screen displays a slice of the i3 desktop, instead of only the Dota application appearing on screen.
* The top of the Dota screen is cut off visually. It is also inaccessible to the mouse. Game buttons at the top of the screen are unreachable, for example. A screenshot can be seen here: https://i.imgur.com/yOf0O9J.png

The game appeared to display correctly at first, but switching workspaces (Super+2 and then back to Dota with Super+1), caused the screen to display incorrectly as described.

## Expected Behavior

The full-screen game window should take up 100% of the computer screen, and 100% of the game content should be displayed. Switching workspaces should not permanently change the game display.

## Reproduction Instructions

Install and run i3
Install and run Dota 2
Switch workspaces with Super+2, and then return to Dota with Super+1
Observe incorrect screen space allotment

## Environment

Output of `i3 --moreversion 2>&-`:

```
Binary i3 version:  4.16.1 (2019-01-27) © 2009 Michael Stapelberg and contributors
Running version: < 4.2-200
```

I encountered this bug in Ubuntu 19.10 x86_64, with i3-wm version `4.16.1-1` (according to apt).
I also encountered it in the Regolith desktop environment (a fork of i3 with aesthetic tweaks) version `2.47-1ubuntu1~ppa1`. 
I confirmed that the bug does not exist when launching and using Dota in GNOME.

Config:

```
# This file has been auto-generated by i3-config-wizard(1).
# It will not be overwritten, so edit it as you like.
#
# Should you change your keyboard layout some time, delete
# this file and re-run i3-config-wizard(1).
#

# i3 config file (v4)
#
# Please see https://i3wm.org/docs/userguide.html for a complete reference!

set $mod Mod4

# Font for window titles. Will also be used by the bar unless a different font
# is used in the bar {} block below.
font pango:monospace 20

# This font is widely installed, provides lots of unicode glyphs, right-to-left
# text rendering and scalability on retina/hidpi displays (thanks to pango).
#font pango:DejaVu Sans Mono 8

# Before i3 v4.8, we used to recommend this one as the default:
# font -misc-fixed-medium-r-normal--13-120-75-75-C-70-iso10646-1
# The font above is very space-efficient, that is, it looks good, sharp and
# clear in small sizes. However, its unicode glyph coverage is limited, the old
# X core fonts rendering does not support right-to-left and this being a bitmap
# font, it doesn’t scale on retina/hidpi displays.

# Use Mouse+$mod to drag floating windows to their wanted position
floating_modifier $mod

# start a terminal
bindsym $mod+Return exec i3-sensible-terminal

# kill focused window
bindsym $mod+Shift+q kill

# start dmenu (a program launcher)
# bindsym $mod+d exec dmenu_run
# There also is the (new) i3-dmenu-desktop which only displays applications
# shipping a .desktop file. It is a wrapper around dmenu, so you need that
# installed.
# bindsym $mod+d exec --no-startup-id i3-dmenu-desktop
bindsym $mod+d exec --no-startup-id j4-dmenu-desktop

# change focus
bindsym $mod+j focus left
bindsym $mod+k focus down
bindsym $mod+l focus up
bindsym $mod+semicolon focus right

# alternatively, you can use the cursor keys:
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

# move focused window
bindsym $mod+Shift+j move left
bindsym $mod+Shift+k move down
bindsym $mod+Shift+l move up
bindsym $mod+Shift+semicolon move right

# alternatively, you can use the cursor keys:
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

# split in horizontal orientation
bindsym $mod+h split h

# split in vertical orientation
bindsym $mod+v split v

# enter fullscreen mode for the focused container
bindsym $mod+f fullscreen toggle

# change container layout (stacked, tabbed, toggle split)
bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+e layout toggle split

# toggle tiling / floating
bindsym $mod+Shift+space floating toggle

# change focus between tiling / floating windows
bindsym $mod+space focus mode_toggle

# focus the parent container
bindsym $mod+a focus parent

# focus the child container
#bindsym $mod+d focus child

# Define names for default workspaces for which we configure key bindings later on.
# We use variables to avoid repeating the names in multiple places.
set $ws1 "1"
set $ws2 "2"
set $ws3 "3"
set $ws4 "4"
set $ws5 "5"
set $ws6 "6"
set $ws7 "7"
set $ws8 "8"
set $ws9 "9"
set $ws10 "10"

# switch to workspace
bindsym $mod+1 workspace $ws1
bindsym $mod+2 workspace $ws2
bindsym $mod+3 workspace $ws3
bindsym $mod+4 workspace $ws4
bindsym $mod+5 workspace $ws5
bindsym $mod+6 workspace $ws6
bindsym $mod+7 workspace $ws7
bindsym $mod+8 workspace $ws8
bindsym $mod+9 workspace $ws9
bindsym $mod+0 workspace $ws10

# move focused container to workspace
bindsym $mod+Shift+1 move container to workspace $ws1
bindsym $mod+Shift+2 move container to workspace $ws2
bindsym $mod+Shift+3 move container to workspace $ws3
bindsym $mod+Shift+4 move container to workspace $ws4
bindsym $mod+Shift+5 move container to workspace $ws5
bindsym $mod+Shift+6 move container to workspace $ws6
bindsym $mod+Shift+7 move container to workspace $ws7
bindsym $mod+Shift+8 move container to workspace $ws8
bindsym $mod+Shift+9 move container to workspace $ws9
bindsym $mod+Shift+0 move container to workspace $ws10

# reload the configuration file
bindsym $mod+Shift+c reload
# restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym $mod+Shift+r restart
# exit i3 (logs you out of your X session)
bindsym $mod+Shift+e exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -b 'Yes, exit i3' 'i3-msg exit'"

# resize window (you can also use the mouse for that)
mode "resize" {
        # These bindings trigger as soon as you enter the resize mode

        # Pressing left will shrink the window’s width.
        # Pressing right will grow the window’s width.
        # Pressing up will shrink the window’s height.
        # Pressing down will grow the window’s height.
        bindsym j resize shrink width 10 px or 10 ppt
        bindsym k resize grow height 10 px or 10 ppt
        bindsym l resize shrink height 10 px or 10 ppt
        bindsym semicolon resize grow width 10 px or 10 ppt

        # same bindings, but for the arrow keys
        bindsym Left resize shrink width 10 px or 10 ppt
        bindsym Down resize grow height 10 px or 10 ppt
        bindsym Up resize shrink height 10 px or 10 ppt
        bindsym Right resize grow width 10 px or 10 ppt

        # back to normal: Enter or Escape or $mod+r
        bindsym Return mode "default"
        bindsym Escape mode "default"
        bindsym $mod+r mode "default"
}

bindsym $mod+r mode "resize"

# Start i3bar to display a workspace bar (plus the system information i3status
# finds out, if available)
bar {
        status_command i3status
  colors {
    separator #dc322f
    background #002b36
    statusline #268bd2
    focused_workspace #fdf6e3 #859900 #fdf6e3
    active_workspace #fdf6e3 #6c71c4 #fdf6e3
    inactive_workspace #586e75 #93a1a1 #002b36
    urgent_workspace #d33682 #d33682 #fdf6e3
  }
}

for_window [class="^.*"] border pixel 0

# gaps inner 15
# gaps outer 0

exec --no-startup-id i3-battery-popup -n
exec --no-startup-id xsetroot -solid "#735CDD"
# exec --no-startup-id feh --bg-no-scale /home/ben/Dropbox/pictures/Desktop/wallhaven-735928.jpg

client.focused #859900 #859900 #fdf6e3 #6c71c4
client.focused_inactive #073642 #073642 #eee8d5 #6c71c4
client.unfocused #073642 #073642 #93a1a1 #586e75
client.urgent #d33682 #d33682 #fdf6e3 #dc322f

# Screen Shots
bindsym Print exec scrot '%Y-%m-%d-%s_screenshot_$wx$h.jpg' -e 'mv $f ~/db/Pictures/Screenshots'
bindsym Control+Print exec gnome-screenshot -ic

```

<pre>
- Linux Distribution & Version: Ubuntu 19.10 x86_64 
- Are you using a compositor (e.g., xcompmgr or compton): No
</pre>

**Comment by BenQuigley** [comment] 2020-02-03 17:42
Screenshot of problem: https://i.imgur.com/yOf0O9J.png

**Comment by Airblader** [comment] 2020-02-03 17:55
> Install and run Dota 2

Dota 2 is not open source (and particularly not free), so we can't support issues regarding it.

> I encountered this bug in Ubuntu 19.10 x86_64, with i3-wm

Which means (correct me if I'm wrong) the issue is not specific to i3-gaps, so please report this upstream. :-) Please also provide a log file when doing so. I'll close this here as not specific to i3-gaps. 

> - Are you using a compositor (e.g., xcompmgr or compton): No

Are you sure?

**Closed as completed by Airblader** 2020-02-03 17:55 UTC

**Comment by BenQuigley** [comment] 2020-02-03 18:04
> Dota 2 is not open source (and particularly not free), so we can't support issues regarding it.

It is free to play & install (I know the word "free" has other meanings in a FOSS software context, just not sure what you meant).

For what it's worth other full-screen Steam games are working fine, so maybe the issue is with Dota itself.

I will update the ticket (after I move it to the upstream repo) if I see what appears to be the same bug affect another program.

> Which means (correct me if I'm wrong) the issue is not specific to i3-gaps, so please report this upstream.

Oops, you're right, thank you. I forgot this repository wasn't i3 itself.

> Please also provide a log file when doing so.

Will do.

**Comment by BenQuigley** [comment] 2020-02-03 18:09
> > Are you using a compositor (e.g., xcompmgr or compton): No

> Are you sure?

Not at all.

Also, ooh, I just realized that toggling full screen with Super+F fixes this!
