### ISSUE TITLE
i3 borders not showing when split windows are inside a tabbed window

### ISSUE THREAD

**Issue by stonewareslord** [Airblader/i3#87] opened 2016-06-02 00:09 UTC
Output of `i3 --moreversion 2>&- || i3 --version`:

```
Binary i3 version:  4.12 (2016-03-06, branch "4.12") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.12 (2016-03-06, branch "4.12") (pid 25730)
Loaded i3 config: /home/stonewareslord/.i3/config (Last modified: Wed 01 Jun 2016 06:28:21 PM EDT, 5228 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: /usr/bin/i3
```

URL to a logfile as per http://i3wm.org/docs/debugging.html:

https://bpaste.net/show/9e567b8b5254

**What I did:**

Open window 1, open window 2, change layout to tabbed, split window vertically/horizontally, open window 3

**What I saw:**

No borders were drawn around windows 1, 2, or 3

**What I expected instead:**

Borders around windows 2 and 3

Here's a screenshot of two windows side by side with no parent (this is drawn correctly):
![selection_007](https://cloud.githubusercontent.com/assets/7482347/15729682/7fa49ad4-2834-11e6-95d6-b9e9925a64b8.png)

Here's a screenshot of two windows side by side when their parent is a tabbed or stacked layout (drawn incorrectly -- these two should have borders):
![selection_008](https://cloud.githubusercontent.com/assets/7482347/15729688/8d989c58-2834-11e6-811e-150ff15b7e3b.png)

**Comment by Airblader** [comment] 2016-06-02 08:43
Can you reproduce this with vanilla i3?

**Comment by stonewareslord** [comment] 2016-06-02 09:34
No I can not.

But I did just try commenting out `smart_borders on` from my config file and the windows are drawing correctly now, so it looks like it's a problem with `smart_borders`

**Comment by Airblader** [comment] 2016-06-02 10:32
I can't reproduce this, even with `workspace_layout tabbed`. But I agree that this is wrong and should be fixed.

**Comment by Airblader** [comment] 2016-08-18 20:47
@stonewareslord I just now saw that you were using the 4.12 release tag. Can you actually test this on the current gaps-next branch HEAD? I think we did have a change in the smart_borders logic pulled in by a change in upstream, so maybe it was just fixed in the meantime.

**Comment by Airblader** [comment] 2016-09-24 22:12
I'm closing now since there's been no more feedback. Let me know if you can reproduce it with the current development version still and I'll reopen.

**Closed as completed by Airblader** 2016-09-24 22:12 UTC
Labels: bug
