### ISSUE TITLE
Window title not moved with container, didn't disappear on close of window.

### ISSUE THREAD

**Issue by Unip0rn** [Airblader/i3#110] opened 2016-11-12 01:06 UTC
Output of `i3 --moreversion 2>&- || i3 --version`:
Binary i3 version:  4.12-non-git © 2009 Michael Stapelberg and contributors
Running i3 version: 4.12-non-git (pid 1219)l-c to abort…)
Loaded i3 config: /home/yuno/.config/i3/config (Last modified: Thu 10 Nov 2016 09:12:24 PM CET, 103349 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

11/12/2016 01:55:56 AM - Additional arguments passed. Sending them as a command to i3.
[{"success":false,"parse_error":true,"error":"Expected one of these tokens: <end>, '[', 'move', 'exec', 'exit', 'restart', 'reload', 'shmlog', 'debuglog', 'border', 'layout', 'append_layout', 'workspace', 'focus', 'kill', 'open', 'fullscreen', 'sticky', 'split', 'floating', 'mark', 'unmark', 'resize', 'rename', 'nop', 'scratchpad', 'title_format', 'mode', 'bar', 'gaps'","input":"version output","errorposition":"^^^^^^^^^^^^^^"}]

URL to a logfile as per http://i3wm.org/docs/debugging.html:

Sorry, no logfile, will be submit when reproduced

**What I did:**

Randomly move container trying to get a certain layout using 
Mod4+[Key for desired direction] to move focus and 
Mod4+Shift+[Key for desired direction] to move container to that direction

**What I saw:**

on split layout window title didnt move with the container containing it, but container moved.
on close of one of the windows the title stayed

**What I expected instead:**

window title should have moved with moved container
window title should have been deleted on close of window.

**Comment by Airblader** [comment] 2016-11-12 01:36
Can you please also provide a screenshot (better yet, video – but image will do for now) of the situation? Are you running a compositor?

**Comment by Unip0rn** [comment] 2016-11-12 01:37
no compositor, looking for extraction of logfile atm found way to reproduce, video on progrss, log in progress

**Comment by Airblader** [comment] 2016-11-12 01:38
Can you try running a compositor? This may well be a video driver issue.

**Comment by Unip0rn** [comment] 2016-11-12 01:40
not experienced on compositors yet, GPU is nVidia GT 670 MX if that helps
added compositor to personal todos on that issue

**Comment by Airblader** [comment] 2016-11-12 01:40
Just running compton without configuring it at all should be a good place to start. Thanks!

**Comment by Unip0rn** [comment] 2016-11-12 01:56
reproduced with compton same way as before:
opened thunderbird, telegram-dektop-dark, qpaeq, TS3.
split horizontal
move thunderbird to left
move qpaeq down
move thunderbird left
open terminator
focus terminator
switch to layout tabbed
switch to layout split
move terminator left

reproduced, may close terminator, title still stays
aso found this to be easily resolvable by focusing terminator and toggling switch and moving terminator and thunderbird out.

running Arch x64, up-to-date on all packages, GT670MX with nouveau

**Comment by Airblader** [comment] 2016-11-12 01:59
Thanks. I don't think we need screenshot / video anymore, it's pretty clear to me _what_ is going wrong. As a last favor, can you switch to vanilla i3 and reproduce the issue there (which I assume you will be able to) and then report it upstream in i3/i3?

It seems like for some specific case we're not invalidating the deco_render_params. The fact that the re-focus trick works makes this pretty obvious to me.

**Comment by Unip0rn** [comment] 2016-11-12 02:00
working on it

**Comment by Unip0rn** [comment] 2016-11-12 02:08
Sorry, not reproduced on i3-vanilla, will retry with gaps disabled on i3-gaps

**Comment by Airblader** [comment] 2016-11-12 02:10
Ah, then the issue isn't the caching but the fact that you're using window titles with gaps. That's not something i3-gaps supports currently, sorry. :-( It works "mostly" nowadays, but just not quite right. The change to make this work correctly is a relatively large change in i3 which I haven't had time to work on in a while now.

**Comment by Airblader** [comment] 2016-11-12 02:11
Addendum: see README on gaps:

> Note: Gaps will only work correctly if you disable window titlebars entirely. Unfortunately this is necessary due to the way i3 creates such bars on windows. […]

**Comment by Unip0rn** [comment] 2016-11-12 02:21
found problematic line in config: new_window none

not reproduced on i3-vanilla,
not reproduced on i3-gaps with window titles enabled (no line 'new_window none')
reproduced on i3-gaps with problematicl ine enabled
not moved to i3
EDIT: new_window none not the only part of problem, also gaps enabled required for reproduction.
gaps and smart_gaps produce different result

**Comment by Airblader** [comment] 2016-11-12 02:24
OK, that sure sounds interesting. In that case I would like the screenshot after all. Thanks for your quick answers. :-) 

However, it's 3:30am here so I'll continue this another time. :-)

**Comment by Unip0rn** [comment] 2016-11-12 03:57
http://imgur.com/a/wO7sT
both with gaps and smart_gaps, as in pic description

and no problem since you answered so quick :+1:

**Comment by Airblader** [comment] 2020-12-31 08:25
This was now four years ago, and not a single other user ever reported this, so I'm very inclined to say this isn't an issue with i3-gaps. I'll close this for now due to the age and many changes since, but if it still occurs please let me know.

**Closed as completed by Airblader** 2020-12-31 08:25 UTC
Labels: bug
