### ISSUE TITLE
Use gaps as resize handles

### ISSUE THREAD

**Issue by PMunch** [Airblader/i3#100] opened 2016-09-17 10:24 UTC
In regular i3 you can resize windows by using the mouse and dragging the border between two windows. This is a practical feature if you need to use the mouse for something or have a touch-screen. However in i3-gaps most people tend to have very small borders and to use the gaps as bordering. If possible I'd really like to see the gaps between two windows work like the border of a regular i3 window in that they can be clicked and dragged to resize the window. This would make it a lot easier to change the size of a window when using a mouse or touch-screen with i3-gaps.

**Comment by Airblader** [comment] 2016-09-17 10:31
> However in i3-gaps most people tend to have very small borders and to use the gaps as bordering

Gaps are not borders, that's what borders are for.

> If possible I'd really like to see the gaps between two windows work like the border of a regular i3 window in that they can be clicked and dragged to resize the window.

Why not just have the mouse at the edge of the window and press the modifier key? This snaps the cursor and allows the resize even without borders.

Also, implementing this would be significantly complex since gaps are unoccupied space. There's no window to grab, so it'd have to all be done on the root window. I'm not looking for this kind of big changes since my focus for i3-gaps is keeping it up to date with upstream. But if somebody wants to provide a pull request showing that it's not all that complicated I would perhaps reconsider. I won't be working on this myself, though.

**Comment by Airblader** [comment] 2016-09-17 10:34
As a »workaround« you can use actual borders and use `#00000000` as the child_border color (and not use gaps). Then the border resize functionality works. The downside being that it's borders, so the »gaps« between windows are double of those at the screen edge.

Combine that with one border width of outer gaps and even that issue disappears.

**Comment by Airblader** [comment] 2016-09-17 10:38
Here's a screenshot that shows the setup I describe above. I've changed my wallpaper so that it's easier to see.

![screenshot-2016-09-17_12-37-23](https://cloud.githubusercontent.com/assets/2392216/18607671/a6e72e92-7cd3-11e6-8cf0-98281d5f007a.png)

**Comment by PMunch** [comment] 2016-09-17 10:43
I can't get the snapping feature to work. I came about this when working on my [https://www.reddit.com/r/i3wm/comments/52wgst/i3_with_touch_controls/](i3 with touch controls) project so using the modifier wouldn't really work in that case either. Well there are no windows to grab but a simple solution would be to determine which window to resize (based on the i3 layout this shouldn't be too hard) and then enable resizing on that window. I might look into it myself, but thanks for the workaround, that will be helpful.

**Comment by Airblader** [comment] 2016-09-17 10:45
I'll leave the issue open since I would consider it in case the pull request convinces me, but please note that it will highly depend on what it looks like. In general I'm not opposed to the idea.

**Comment by Airblader** [comment] 2016-09-17 10:48
@PMunch One more thing – it's very unlikely that i3 will ever improve much regarding touch control. I think you might have a better shot trying to work with @SirCmpwn on https://github.com/SirCmpwn/sway. Perhaps they'd be interested in touch control features? Gaps are also a built-in core feature in sway. There is https://github.com/SirCmpwn/sway/issues/721 but I'm not sure if there's other efforts or plans.

**Comment by cody-pa** [comment] 2017-09-28 06:11
I'd like to pop in and mention that for me, the transparent border trick only seems to work on some windows, not all; a couple of my windows (such as firefox and atom) don't seem to support ARGB in their borders. The google-fu I did implied that it's a problem with the window color depth, though I'm not sure how to actually check that myself, or whether it's possible for i3 to deal with that.

EDIT: Or it might be caused by gtk2. Not quite sure.

**Comment by ktmorris21** [comment] 2017-11-09 01:42
I came across this same question/issue and, while Googling solutions, found the following somewhere along the way. Thought I would share it here for future folks looking for a simple workaround as it worked perfectly for me.

You can hold the modifier key and right-click (and hold) on the window to be resized, which will then allow you to resize using the mouse.

**Comment by Airblader** [comment] 2018-11-03 20:06
Closing now because using the modifier key works and I think that is reasonable enough.

**Closed as completed by Airblader** 2018-11-03 20:06 UTC
Labels: enhancement
