### ISSUE TITLE
Wrong values when resizing floating window 

### ISSUE THREAD

**Issue by aacebedo** [Airblader/i3#369] opened 2020-10-05 08:23 UTC
## I'm submitting a…
<pre>
[x] Bug
</pre>

## Current Behavior
i3-msg resize set command changes the size but the values are incorrect.
```
i3-msg [con_id=#window_id] resize set 640 480
I3-msg -t get_tree   
```

values of the window:
```
"current_border_width": 0,
                      "rect": {
                        "x": 0,
                        "y": 0,
                        "width": 645,
                        "height": 370
                      },
                      "deco_rect": {
                        "x": 0,
                        "y": 0,
                        "width": 0,
                        "height": 0
                      },
                      "window_rect": {
                        "x": 0,
                        "y": 0,
                        "width": 645,
                        "height": 370
                      },
                      "geometry": {
                        "x": 0,
                        "y": 0,
                        "width": 653,
                        "height": 438
                      },
```
I have no borders on windows. The illustrated window it a xfce4-terminal window with scrollbar and toolbar shown. If I hide those two elements I am getting a closer value but still not the correct one.

```
"current_border_width": 0,
"rect": {
                        "x": 0,
                        "y": 0,
                        "width": 642,
                        "height": 359
                      },
                      "deco_rect": {
                        "x": 0,
                        "y": 0,
                        "width": 0,
                        "height": 0
                      },
                      "window_rect": {
                        "x": 0,
                        "y": 0,
                        "width": 642,
                        "height": 359
                      },
                      "geometry": {
                        "x": 0,
                        "y": 0,
                        "width": 653,
                        "height": 438
                      },
```

## Expected Behavior
The size of the window including the menubar and the scroll bar have the values given in the i3-msg command

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.18.2-229-g234d6855 (2020-09-02, branch "gaps-next") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.18.2-229-g234d6855 (2020-09-02, branch "gaps-next") (pid 629107)
Loaded i3 config: /home/aacebedo/.config/i3/config (Last modified: lun. 05 oct. 2020 09:51:44, 1667 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

<details><summary>Config file</summary><pre>
`set $mod Mod4

font -misc-fixed-medium-r-normal--13-120-75-75-C-70-iso10646-1
font pango:Noto Sans Bold 10

for_window [class=".*"] title_format "<b>%title</b>"
title_align center

floating_modifier $mod
workspace_layout default

set_from_resource $active_bg_color i3.active_bg_color #FFFFFF
set_from_resource $inactive_bg_color i3.inactive_bg_color #FFFFFF
set_from_resource $important_bg_color i3.important_bg_color #FFFFFF
set_from_resource $active_txt_color i3.active_txt_color #FFFFFF
set_from_resource $inactive_txt_color i3.inactive_txt_color #FFFFFF
set_from_resource $important_txt_color i3.important_txt_color #FFFFFF
set_from_resource $wallpaper i3.wallpaper none

# start a terminal
bindsym $mod+Return exec i3-sensible-terminal

# kill focused window
bindsym $mod+q [con_id=__focused__ title="^(?!Tilda - .*)"] kill

# alternatively, you can use the cursor keys:
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right
bindsym $mod+a focus parent
bindsym $mod+c focus child

# alternatively, you can use the cursor keys:
bindsym $mod+Shift+Left [con_id=__focused__ title="^(?!Tilda - .*)"] move left
bindsym $mod+Shift+Down [con_id=__focused__ title="^(?!Tilda - .*)"] move down
bindsym $mod+Shift+Up [con_id=__focused__ title="^(?!Tilda - .*)"] move up
bindsym $mod+Shift+Right [con_id=__focused__ title="^(?!Tilda - .*)"] move right

# split in horizontal orientation
bindsym $mod+h split h

# split in vertical orientation
bindsym $mod+v split v

# Toggle splitorientation
bindsym $mod+Shift+s split s

# enter fullscreen mode for the focused container
bindsym $mod+f [con_id=__focused__ title="^(?!Tilda - .*)"] fullscreen toggle
popup_during_fullscreen ignore

# change container layout (stacked, tabbed, toggle split)
bindsym $mod+e layout stacking
bindsym $mod+t layout tabbed
bindsym $mod+d layout default
bindsym $mod+s layout toggle split

# toggle tiling / floating
bindsym $mod+Shift+space [con_id=__focused__ title="^(?!Tilda - .*)"] floating toggle

# change focus between tiling / floating windows
bindsym $mod+space [con_id=__focused__ title="^(?!Tilda - .*)"] focus mode_toggle

# switch to workspace
bindsym $mod+ampersand workspace 1
bindsym $mod+eacute workspace 2
bindsym $mod+quotedbl workspace 3
bindsym $mod+apostrophe workspace 4
bindsym $mod+parenleft workspace 5
bindsym $mod+minus workspace 6
bindsym $mod+egrave workspace 7
bindsym $mod+underscore workspace 8
bindsym $mod+ccedilla workspace 9
bindsym $mod+agrave workspace 10
bindsym $mod+Page_Down workspace prev
bindsym $mod+Page_Up workspace next

# move focused container to workspace
bindsym $mod+Shift+ampersand move container to workspace 1
bindsym $mod+Shift+eacute move container to workspace 2
bindsym $mod+Shift+quotedbl move container to workspace 3
bindsym $mod+Shift+apostrophe move container to workspace 4
bindsym $mod+Shift+5 move container to workspace 5
bindsym $mod+Shift+minus move container to workspace 6
bindsym $mod+Shift+egrave move container to workspace 7
bindsym $mod+Shift+underscore move container to workspace 8
bindsym $mod+Shift+ccedilla move container to workspace 9
bindsym $mod+Shift+agrave move container to workspace 10

# reload the configuration file
bindsym $mod+Shift+r reload
bindsym $mod+Shift+e exec "i3-msg exit"

# resize window (you can also use the mouse for that)
mode "resize" {
      # same bindings, but for the arrow keys
      bindsym Left resize shrink width 10 px or 10 ppt
      bindsym Down resize grow height 10 px or 10 ppt
      bindsym Up resize shrink height 10 px or 10 ppt
      bindsym Right resize grow width 10 px or 10 ppt

      # back to normal: Enter or Escape
      bindsym Return mode "default"
      bindsym Escape mode "default"
}

bindsym $mod+r mode "resize"

client.focused          $active_bg_color    $active_bg_color    $active_txt_color    $important_bg_color
client.focused_inactive $inactive_bg_color  $inactive_bg_color  $inactive_txt_color  $inactive_bg_color
client.unfocused        $inactive_bg_color  $inactive_bg_color  $inactive_txt_color  $inactive_bg_color
client.urgent           $important_bg_color $important_bg_color $important_txt_color $important_bg_color

#default_border pixel 3
hide_edge_borders both
default_border pixel 0
gaps inner 5
gaps outer 0
gaps top 30

exec --no-startup-id picom
exec --no-startup-id tilda
exec --no-startup-id flashfocus
exec --no-startup-id /usr/lib/xfce-polkit/xfce-polkit
exec --no-startup-id blueman-applet
exec --no-startup-id polybar top
exec --no-startup-id xfsettingsd
exec --no-startup-id ~/.config/i3/scripts/set_background $wallpaper
exec --no-startup-id xfce4-power-manager
exec --no-startup-id light-locker
exec --no-startup-id nm-applet
exec --no-startup-id conky -c ~/.config/conky/conkyrc_right
exec --no-startup-id conky -c ~/.config/conky/conkyrc_left
exec --no-startup-id sh -c 'sleep 4; exec seafile-applet'
exec --no-startup-id parsecd app_console=1
exec --no-startup-id /usr/lib/xfce4/notifyd/xfce4-notifyd
exec --no-startup-id telegram-desktop -startintray
exec --no-startup-id greenclip daemon
exec --no-startup-id pnmixer 

bindsym $mod+Shift+p [con_id=__focused__ title="^(?!Tilda - .*)" floating] move scratchpad
bindsym $mod+p scratchpad show
</pre>
</details>

<pre>
- Linux Distribution & Version: Manjaro latest
- Are you using a compositor : Yes picom vgit-2c9e7
</pre>

**Comment by orestisfl** [comment] 2020-10-05 08:31
Can you please reproduce with https://github.com/i3/i3 and send a report there if it applies?

**Comment by orestisfl** [comment] 2020-10-05 08:34
Another thing, does your window specify width/height increments? Because i3 respects these:

https://github.com/i3/i3/blob/04c489043c5caf2d4c07f16bf9606de581dc9800/src/floating.c#L782-L790

You can check using `xprop WM_NORMAL_HINTS` and then select your window

**Comment by aacebedo** [comment] 2020-10-05 08:41
Thanks for the response !
I can't change my setup to i3 vanilla right now.

Checked the command and gave me this:
```
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified minimum size: 277 by 58
		program specified resize increment: 8 by 17
		program specified base size: 13 by 30
		window gravity: NorthWest
```

How can I change the incorement ?
How do I shall understand 8 by 17 ? I is not a simple integer value. The increment value does not appear on i3 tree.

**Comment by orestisfl** [comment] 2020-10-05 12:34
> How can I change the incorement ?

I am not sure if it's that easy with current tools e.g: https://superuser.com/questions/426961/howto-set-wm-normal-hints-with-xprop

> How do I shall understand 8 by 17 ? 

I think it means that the width increment is 8 and the height is 17

**Comment by aacebedo** [comment] 2020-10-06 08:57
Just tried with i3 vanilla, same issue.

**Comment by Airblader** [comment] 2020-10-06 09:05
Thanks for reporting it there, I'll close this as this is now tracked upstream.

BTW @orestisfl thanks for helping out here on i3-gaps as well. If you don't mind I'll add you as a collaborator on the repository so you could also do all the same things you can do in i3 (whether or not you make use of that is entirely up to you of course)?

**Closed as completed** 2020-10-06 09:05 UTC

**Comment by aacebedo** [comment] 2020-10-06 09:07
Thanks you for the help of you both ! 
Hope we'll get this sorted out. I am writing a small utility in golang to ease the use of floating windows in i3 and I need the positions to be correctly calculated and applied.

**Comment by orestisfl** [comment] 2020-10-06 10:15
@Airblader Yeah sure :)

@aacebedo I don't think there is any plan to change the current implementation in i3, this is not a bug and changing the WM_HINTS is not strictly i3's responsibility. You might be able to write a utility that sets the correct hints using xcb / xlib since xprop can't do it for some reason, or you can debug the xprop code. Sorry I can't be of more help :/

**Comment by Airblader** [comment] 2020-10-06 10:20
Sorry, I hadn't actually read the issue yet. Yes, @orestisfl is correct here: i3 is behaving the way it is supposed to. You'll have to make your script deal with that.

For requests to changes like these the paradigm in X is: a client may request, but the window manager has authority on what to do with that request: fulfill, change or ignore. That's the paradigm that allows tiling window managers to even exist in the first place. As a client you are required not to assume your request to just work but instead wait for the reply from the window manager to see what actually happened and act accordingly.

**Comment by aacebedo** [comment] 2020-10-06 10:39
@orestisfl I can take into account the WM_HINTS without changing it and ask gor size compatible with the increment. I'll look into that. 
The thing bothering me is that the resizing behavior changes if the tool bar or scroll bar are activated. Like the size I give to i3-msg are concerning only the content of the windows without the scroll bar and the menu bar.

@Airblader I'll check if I find some xcb/xlib bindings for golang. 
I haven't worked yet on X related tools. Do you think that I would be able to resize windows with those kind of tools and is it the right way to do it ? My tool is designed to work only with i3 at the end

**Comment by aacebedo** [comment] 2020-10-09 10:25
Updated the bug on i3 repo. 
After some tinkering with xcb my problem si still there.
xcb doesn't resize correctly even if I change the HINTS or provide a divisible width.
