### ISSUE TITLE
Cannot set gaps for specific workspace

### ISSUE THREAD

**Issue by BombchuLink** [Airblader/i3#410] opened 2021-08-24 05:42 UTC
## I'm submitting a…
<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
When adding the line ``workspace "ws" gaps top 5`` to the i3 config file, the workspace ``ws`` does not have the top gap set to 5 (this is set AFTER the global setting of the gaps size in the config file)

## Expected Behavior
the outer gaps to be set to 5 on workspace ``ws``

## Environment
Output of `i3 --moreversion 2>&-`:
Binary i3 version:  4.19.1 (2021-02-01) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.19.1 (2021-02-01) (pid 2066)
Loaded i3 config: /home/blink/.config/i3/config (Last modified: Mon 23 Aug 2021 10:33:29 PM PDT, 98 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

- Linux Distribution & Version:
Arch linux x86_64 - Kernel 5.13.10-arch1-1
- compositor 
xcompmgr

**Comment by Airblader** [comment] 2021-08-24 05:48
Please attach your full config (ideally reduced to a minimum for reproducability) and the output of `i3-msg -t get_tree` after switching to workspace "ws".

**Comment by BombchuLink** [comment] 2021-08-24 16:54
After further investigation; having set the variables for gaps in the i3 config, and doing a complete reboot of xorg, the gaps are properly set; however, the gaps remain unchanged after reloading the i3 config by using ``i3-msg restart``.

I3 config:
```
#--General Rules--#
for_window [class="^.*"] border pixel 2
gaps inner 0
gaps outer 0
set $term --no-startup-id xst
set $mod Mod4
set $alt Mod1
floating_modifier Mod4


#---Window Rules---#
# toggle tiling / floating
bindsym $super+space floating toggle

#start polybar
exec_always --no-startup-id ~/.config/i3/polybar.sh &

#--Window Manipulation--#
bindsym $mod+Return				split horizontal ;; exec $term
bindsym $mod+slash				split vertical ;; exec $term

bindsym $mod+c				floating toggle
bindsym $mod+space			focus mode_toggle
bindsym $mod+f				fullscreen toggle

bindsym $mod+h				focus left
bindsym $mod+j				focus down
bindsym $mod+k				focus up
bindsym $mod+l				focus right
bindsym $mod+Shift+h		move left 30
bindsym $mod+Shift+j		move down 30
bindsym $mod+Shift+k		move up 30
bindsym $mod+Shift+l		move right 30
bindsym $mod+Shift+y		exec --no-startup-id i3resize left
bindsym $mod+Shift+u		exec --no-startup-id i3resize down
bindsym $mod+Shift+i		exec --no-startup-id i3resize up
bindsym $mod+Shift+o		exec --no-startup-id i3resize right

bindsym $mod+Shift+s		gaps inner current set 0; gaps outer current set 0


#--System--#
bindsym $mod+Shift+r		restart
bindsym $mod+Shift+q		[con_id="__focused__" instance="^(?!dropdown_).*$"] exec --no-startup-id kill -9 `xdotool getwindowfocus getwindowpid`

#--Exit--#
bindsym $mod+Shift+x	 	exec --no-startup-id prompt "Shutdown computer?" "shutdown -h now"
bindsym $mod+Shift+Escape 	exec --no-startup-id changede
bindsym $mod+Shift+BackSpace 	exec --no-startup-id prompt "Reboot PC?" "sudo -A reboot"


workspace ws output HDMI-A-0

workspace ws gaps top 35
workspace ws gaps bottom 50
workspace ws gaps horizontal 85
```

**Comment by Airblader** [comment] 2021-08-24 17:06
Is the workspace already open when you restart i3 or do you open it after the restart?

**Comment by BombchuLink** [comment] 2021-08-24 17:58
If the workspace is open on restart, the changes do not take effect.
If the workspace is not open, the changes do take effect.

**Comment by Airblader** [comment] 2021-08-24 17:59
Thanks for confirming. This is expected behavior as workspace assignments are evaluated on workspace creation. Closing since there doesn't seem to be any issue left now.

**Closed as completed by Airblader** 2021-08-24 17:59 UTC
