### ISSUE TITLE
Error during make: "undefined reference to `g_utf8_make_valid'"

### ISSUE THREAD

**Issue by conorwsullivan** [Airblader/i3#236] opened 2018-09-19 03:38 UTC
## I'm submitting a…
<pre>
[X] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
Can't make

## Expected Behavior
i3-gaps makes and installs normally

## Reproduction Instructions
Fresh install of Debian 9. I installed listed dependencies and build-essentials. 

## Environment
Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 
</pre>

<pre>
</pre>

<pre>
Logfile URL:
</pre>

<pre>
- Linux Distribution & Version: Debian 9
- Are you using a compositor (e.g., xcompmgr or compton): not yet
</pre>

**Comment by Airblader** [comment] 2018-09-19 04:50
Have you read the article on compiling in the wiki here on Github?

**Comment by jacderida** [comment] 2018-09-20 09:29
I was just about to open an issue on this. I have the same problem.

I have an [automated development environment](https://github.com/jacderida/devbox) that uses i3gaps. I tried to run another build of the environment last week and discovered i3gaps was failing to compile on Debian Stretch64. I can give you the steps to reproduce the failure, but I'm not really sure how to diagnose the problem myself, as I'm not a C programmer. I did try looking on Google, but couldn't find anything. I also can't really tell if this is an issue with i3gaps or just i3. My automation is based on your wiki article, and it had been working fine for months until last week.

Here is the resulting error:
```
./libi3.a(libi3_a-string.o): In function `i3string_from_utf8_with_length':
/home/vagrant/i3/build/../../i3/libi3/string.c:59: undefined reference to `g_utf8_make_valid'
collect2: error: ld returned 1 exit status
```

## Steps to Reproduce

Use the [Debian Stretch64 Vagrant box](https://app.vagrantup.com/debian/boxes/stretch64) with the following Vagrantfile:
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "debian/stretch64"
end
```

After creating the Vagrantfile, run `vagrant up`, followed by `vagrant ssh` to connect to the box.

Now take the following steps:
```shell
sudo apt-get install -y git
sudo apt-get install -y libev-dev libpango1.0-dev libstartup-notification0-dev libxcb1-dev libxcb-xkb-dev libxcb-cursor-dev libxcb-icccm4-dev libxcb-keysyms1-dev libxcb-randr0-dev libxcb-xinerama0-dev libxcb-util0-dev libxcb-xrm-dev libxcb-xrm0 libxkbcommon-dev libxkbcommon-x11-dev libyajl-dev xcb
git clone https://www.github.com/Airblader/i3
cd i3
autoreconf --force --install
mkdir build && cd build
../configure --prefix=/usr --sysconfdir=/etc --disable-sanitizers
make -j8
```

The build will result in an error:
```
make  all-am
make[1]: Entering directory '/home/vagrant/i3/build'
  CC       libi3/libi3_a-dpi.o
  CC       libi3/libi3_a-draw_util.o
  CC       libi3/libi3_a-fake_configure_notify.o
  CC       libi3/libi3_a-font.o
  CC       libi3/libi3_a-format_placeholders.o
  CC       libi3/libi3_a-get_colorpixel.o
  CC       libi3/libi3_a-get_config_path.o
  CC       libi3/libi3_a-get_exe_path.o
  CC       libi3/libi3_a-get_process_filename.o
  CC       libi3/libi3_a-get_visualtype.o
  CC       libi3/libi3_a-get_mod_mask.o
  CC       libi3/libi3_a-ipc_connect.o
  CC       libi3/libi3_a-ipc_recv_message.o
  CC       libi3/libi3_a-ipc_send_message.o
  CC       libi3/libi3_a-is_debug_build.o
  CC       libi3/libi3_a-mkdirp.o
  CC       libi3/libi3_a-resolve_tilde.o
  CC       libi3/libi3_a-root_atom_contents.o
  CC       libi3/libi3_a-safewrappers.o
  CC       libi3/libi3_a-string.o
  CC       libi3/libi3_a-strndup.o
  CC       libi3/libi3_a-ucs2_conversion.o
  CC       src/i3-assignments.o
  CC       src/i3-bindings.o
../../i3/libi3/string.c: In function ‘i3string_from_utf8_with_length’:
../../i3/libi3/string.c:59:17: warning: implicit declaration of function ‘g_utf8_make_valid’ [-Wimplicit-function-declaration]
     str->utf8 = g_utf8_make_valid(from_utf8, num_bytes);
                 ^~~~~~~~~~~~~~~~~
../../i3/libi3/string.c:59:15: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
     str->utf8 = g_utf8_make_valid(from_utf8, num_bytes);
               ^
  CC       src/i3-click.o
  CC       src/i3-commands.o
  GEN      i3-command-parser.stamp
  CC       src/i3-con.o
  CC       src/i3-config.o
  CC       src/i3-config_directives.o
  GEN      i3-config-parser.stamp
  CC       src/i3-display_version.o
  CC       src/i3-ewmh.o
  CC       src/i3-fake_outputs.o
  CC       src/i3-floating.o
  CC       src/i3-handlers.o
  CC       src/i3-ipc.o
  CC       src/i3-key_press.o
  CC       src/i3-load_layout.o
  CC       src/i3-log.o
  CC       src/i3-main.o
  CC       src/i3-manage.o
  CC       src/i3-match.o
  CC       src/i3-move.o
  CC       src/i3-output.o
  CC       src/i3-randr.o
  CC       src/i3-regex.o
  CC       src/i3-render.o
  CC       src/i3-resize.o
  CC       src/i3-restore_layout.o
  CC       src/i3-scratchpad.o
  CC       src/i3-sd-daemon.o
  CC       src/i3-sighandler.o
  CC       src/i3-startup.o
  CC       src/i3-sync.o
  CC       src/i3-tree.o
  CC       src/i3-util.o
  CC       src/i3-version.o
  CC       src/i3-window.o
  CC       src/i3-workspace.o
  CC       src/i3-x.o
  CC       src/i3-xcb.o
  CC       src/i3-xcursor.o
  CC       src/i3-xinerama.o
  CC       i3bar/src/i3bar_i3bar-child.o
  CC       i3bar/src/i3bar_i3bar-config.o
  CC       i3bar/src/i3bar_i3bar-ipc.o
  CC       i3bar/src/i3bar_i3bar-main.o
  CC       i3bar/src/i3bar_i3bar-mode.o
  CC       i3bar/src/i3bar_i3bar-outputs.o
  CC       i3bar/src/i3bar_i3bar-parse_json_header.o
  CC       i3bar/src/i3bar_i3bar-workspaces.o
  CC       i3bar/src/i3bar_i3bar-xcb.o
  CC       i3-config-wizard/i3_config_wizard_i3_config_wizard-main.o
  CC       i3-dump-log/i3_dump_log_i3_dump_log-main.o
  CC       i3-input/i3_input_i3_input-keysym2ucs.o
  CC       i3-input/i3_input_i3_input-main.o
  CC       i3-msg/i3_msg_i3_msg-main.o
  CC       i3-nagbar/i3_nagbar_i3_nagbar-main.o
  AR       libi3.a
ar: `u' modifier ignored since `D' is the default (see `U')
  CC       src/i3-commands_parser.o
  CC       src/i3-config_parser.o
  CCLD     i3-dump-log/i3-dump-log
  CCLD     i3-config-wizard/i3-config-wizard
  CCLD     i3-msg/i3-msg
  CCLD     i3-input/i3-input
./libi3.a(libi3_a-string.o): In function `i3string_from_utf8_with_length':
/home/vagrant/i3/build/../../i3/libi3/string.c:59: undefined reference to `g_utf8_make_valid'
collect2: error: ld returned 1 exit status
Makefile:1538: recipe for target 'i3-config-wizard/i3-config-wizard' failed
make[1]: *** [i3-config-wizard/i3-config-wizard] Error 1
make[1]: *** Waiting for unfinished jobs....
  CCLD     i3bar/i3bar
./libi3.a(libi3_a-string.o): In function `i3string_from_utf8_with_length':
/home/vagrant/i3/build/../../i3/libi3/string.c:59: undefined reference to `g_utf8_make_valid'
collect2: error: ld returned 1 exit status
Makefile:1565: recipe for target 'i3-input/i3-input' failed
make[1]: *** [i3-input/i3-input] Error 1
./libi3.a(libi3_a-string.o): In function `i3string_from_utf8_with_length':
/home/vagrant/i3/build/../../i3/libi3/string.c:59: undefined reference to `g_utf8_make_valid'
collect2: error: ld returned 1 exit status
Makefile:1620: recipe for target 'i3bar/i3bar' failed
make[1]: *** [i3bar/i3bar] Error 1
make[1]: Leaving directory '/home/vagrant/i3/build'
Makefile:1273: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by orestisfl** [comment] 2018-09-20 09:35
I think the issue here is that `g_utf8_make_valid` is available since glib 2.52 but debian stretch has 2.50: https://packages.debian.org/search?keywords=glib2.0

Since the function is not that important, I think we can skip it if not available.

Btw, this is an i3 issue, not an i3-gaps issue.

**Comment by Airblader** [comment] 2018-09-20 11:12
I'll close this issue here since it's an issue in upstream. Thanks :-)

**Closed as completed by Airblader** 2018-09-20 11:12 UTC

**Comment by pkieltyka** [comment] 2019-03-20 15:56
I'm getting this error again when compiling i3-gaps-next master on Arch with glib 2.60

**Comment by orestisfl** [comment] 2019-03-20 16:04
https://github.com/i3/i3/issues/3652

**Comment by pkieltyka** [comment] 2019-03-20 16:07
thank you
