### ISSUE TITLE
i3 is glitching

### ISSUE THREAD

**Issue by OraBB1t** [Airblader/i3#385] opened 2021-01-25 05:07 UTC
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

Sometimes(more than once each session) i3 glitches out. I think 'glitching' is the right word. I have to restart i3 each time to solve this. Below gif explains the situation better.
[https://i.imgur.com/0d5txJy.gif](https://i.imgur.com/0d5txJy.gif)

## Expected Behavior

Not glitch out.

## Reproduction Instructions

I can't identify exactly what causes this. However this didn't happen before. I think something in the latest release causes this(in my end). Or I changed the compositor recently, from compton to picom. Maybe it has to do something with it. I'm not sure. I'll try disabling it. Also will be providing logs.

## Environment

<pre>
i3 version: 4.19
</pre>

Config: [https://bin.idrix.fr/?78c8b79b96dda261#DDY2ajNMsNENbJ2Lfxus68nAhd2DZymJsmg3xqbZjhBP](https://bin.idrix.fr/?78c8b79b96dda261#DDY2ajNMsNENbJ2Lfxus68nAhd2DZymJsmg3xqbZjhBP)

<pre>
- Linux Distribution & Version: Linux version 5.10.9-arch1-1 (linux@archlinux)
- Are you using a compositor (e.g., xcompmgr or compton): picom
</pre>

**Comment by orestisfl** [comment] 2021-01-25 05:40
- Does it happen without picom?
- Which is the exact output of `i3 --version`?

**Comment by AndreiSva** [comment] 2021-01-25 07:04
Sounds like a compositor issue to me. If the issue happens again try running `killall picom` and see if it fixes the issue.

**Comment by OraBB1t** [comment] 2021-01-25 13:27
>     * Does it happen without picom?

I've disabled picom and so far it's good. But it's only been an hour or so. Will keep you updated.
>     * Which is the exact output of `i3 --version`?
i3 version 4.19 (2020-11-15) © 2009 Michael Stapelberg and contributors

**Comment by OraBB1t** [comment] 2021-01-25 13:28
> Sounds like a compositor issue to me. If the issue happens again try running `killall picom` and see if it fixes the issue.

I think so. Will try kil

**Comment by OraBB1t** [comment] 2021-01-25 13:29
Sorry accidentally pressed 'close'

**Comment by OraBB1t** [comment] 2021-01-26 17:15
Haven't had any issues with picom turned off. So we can confirm it's the source of the issue. Sorry I should've done that before posting the issue. Can anyone suggest how can I fix this? Shall I switch to another compositor?

**Comment by Tonus1** [comment] 2021-01-26 20:19
AFAIK no issue here with picom and i3-gaps, Slackware-current.

Perhaps picom settings ? Video card {,driver} ? To dig further we need more input. And perhaps an other place...

**Comment by orestisfl** [comment] 2021-01-26 22:21
Since this is picom-specific, I'll close this issue but please feel free to comment further if you believe that this is caused by i3

**Closed as completed by orestisfl** 2021-01-26 22:21 UTC
