### ISSUE TITLE
`default_border` setting no longer works

### ISSUE THREAD

**Issue by cptchuckles** [Airblader/i3#453] opened 2022-09-23 18:07 UTC
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>
## Current Behavior

All windows open with their titlebars showing, even though I have the line
`default_border pixel 2`
in my config
## Expected Behavior

Titlebars should not appear by default
## Reproduction Instructions

Put the line
`default_border pixel 2`
in a config. Open a window. Observe the presence of a titlebar.
## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version:
Binary i3 version:  4.21 (2022-09-21) © 2009 Michael Stapelberg and contributors
(Getting version from running i3, press ctrl-c to abort…)
[KRunning i3 version: 4.21 (2022-09-21) (pid 2451)
Loaded i3 config:
  /home/grendel/.config/i3/config (main) (last modified: Sun 18 Sep 2022 01:50:55 PM CDT, 429182 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

<details><summary>Config file</summary><pre>
set $mod Mod4
set $term /usr/bin/alacritty
set $class --class
font pango:NotoSans Display SemiCondensed Nerd Font Complete Bold 10
set $up k
set $down j
set $left h
set $right l
floating_modifier $mod
focus_follows_mouse no
bindsym $mod+$left focus left
bindsym $mod+$down focus down
bindsym $mod+$up focus up
bindsym $mod+$right focus right
bindsym $mod+Control+h focus output left
bindsym $mod+Control+l focus output right
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right
bindsym $mod+Shift+$left move left
bindsym $mod+Shift+$down move down
bindsym $mod+Shift+$up move up
bindsym $mod+Shift+$right move right
bindsym $mod+Mod1+$left  move container to output left,  focus output left
bindsym $mod+Mod1+$right move container to output right, focus output right
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right
bindsym $mod+f fullscreen toggle
bindsym $mod+t layout tabbed
bindsym $mod+x layout toggle split
bindsym $mod+z split toggle
bindsym $mod+Shift+f floating toggle
bindsym $mod+v focus mode_toggle
bindsym $mod+Shift+minus move scratchpad
set $ws1 "1"
set $ws2 "2"
set $ws3 "3"
set $ws4 "4"
set $ws5 "5"
set $ws6 "6"
set $ws7 "7"
set $ws8 "8"
set $ws9 "9"
bindsym $mod+1 workspace $ws1
bindsym $mod+2 workspace $ws2
bindsym $mod+3 workspace $ws3
bindsym $mod+4 workspace $ws4
bindsym $mod+5 workspace $ws5
bindsym $mod+6 workspace $ws6
bindsym $mod+7 workspace $ws7
bindsym $mod+8 workspace $ws8
bindsym $mod+9 workspace $ws9
bindsym $mod+n         exec ~/.bin/nextws
bindsym $mod+p         exec "~/.bin/nextws -p"
bindsym $mod+Control+n exec "~/.bin/nextws -u"
bindsym $mod+Shift+1 move container to workspace $ws1; workspace $ws1
bindsym $mod+Shift+2 move container to workspace $ws2; workspace $ws2
bindsym $mod+Shift+3 move container to workspace $ws3; workspace $ws3
bindsym $mod+Shift+4 move container to workspace $ws4; workspace $ws4
bindsym $mod+Shift+5 move container to workspace $ws5; workspace $ws5
bindsym $mod+Shift+6 move container to workspace $ws6; workspace $ws6
bindsym $mod+Shift+7 move container to workspace $ws7; workspace $ws7
bindsym $mod+Shift+8 move container to workspace $ws8; workspace $ws8
bindsym $mod+Shift+9 move container to workspace $ws9; workspace $ws9
bindsym $mod+y resize shrink width 10 px or 1 ppt
bindsym $mod+u resize grow height 10 px or 1 ppt
bindsym $mod+i resize shrink height 10 px or 1 ppt
bindsym $mod+o resize grow width 10 px or 1 ppt
bindsym $mod+c move position center
bindsym $mod+s sticky toggle
bindsym $mod+Shift+c resize set width 1360 px height 890 px, move position center
bindsym $mod+Mod1+c resize set width 1000px height 1000px, move position center
bindsym $mod+Mod1+f floating enable, resize set width 1920 px height 1060px, move position center
bindsym $mod+comma gaps inner current minus 5px
bindsym $mod+period gaps inner current plus 5px
bindsym $mod+slash gaps inner current set 5px
bar {
	position top
	tray_output primary
	status_command i3blocks
	separator_symbol 
}
default_border pixel 2
hide_edge_borders smart
gaps inner 5
gaps outer 0
for_window [   title="alsamixer"    ] floating enable
for_window [   title="TerminalFloat"] floating enable, resize set width 1360px height 890px, move position center
for_window [instance="TerminalFloat"] floating enable, resize set width 1360px height 890px, move position center
for_window [instance="CtrlAltDel"   ] floating enable, resize set width 1920px height 1060px, move position center
for_window [   class="Gimp"         ] floating enable, resize set width 1920px height 1060px, move position center
for_window [   class="[Ss]xiv"      ] floating enable, resize set width 1920px height 1060px, move position center
for_window [   class="Blender"      ] floating enable, move position center
for_window [   class="UE4Editor"    ] floating enable, move position center
for_window [   class="code-oss"     ] floating enable, move position center
for_window [   class="feh"          ] floating enable, move position center
for_window [class="Pinta" window_type="normal"] floating enable, resize set width 1920 px height 1060px, move position center
for_window [instance="Godot_(?:Editor|ProjectList)"] floating enable
for_window [instance="Godot_Engine" class="^(?!Godot).*"] floating enable, border normal
for_window [instance="Godot_Editor" class="^Godot$"] resize set width 1920 px height 1060px, move position center
for_window [class="mpv"] floating enable, resize set width 720px height 480px, move position center, move right 600px, sticky enable, focus
for_window [window_type="dialog"] floating enable, move position center
for_window [class="Xdialog"] floating enable, move position center
for_window [class="[Pp]inentry.*"] move position center
for_window [class="PAVU"] move scratchpad
for_window [title="DOOMEternal"] floating enable, move position 0px 0px, resize set width 1920 px height 1080px, focus
bindsym $mod+Mod1+r reload
bindsym $mod+Shift+r restart
bindsym $mod+Shift+e exec --no-startup-id "~/.bin/i3exit.sh"
bindsym $mod+BackSpace border toggle
bindsym $mod+Shift+BackSpace kill
bindsym $mod+minus                 exec --no-startup-id "~/.bin/i3getscratch"
bindsym $mod+XF86MonBrightnessDown exec --no-startup-id "~/.bin/togglescreen.sh"
bindsym $mod+Control+k             exec --no-startup-id "~/.bin/setkeyboard.sh"
bindcode --release Mod1+49                   exec "dunstctl history-pop"
bindsym  --release Control+space             exec "dunstctl close"
bindsym  --release Shift+Control+space       exec "dunstctl close-all"
bindsym $mod+d                     exec --no-startup-id dmenu_run
bindsym $mod+a                     exec --no-startup-id "~/.apps/launcher.sh"
bindsym $mod+0                     exec --no-startup-id "~/.bin/slock"
bindsym $mod+Mod1+p                exec "pidof -q picom && pkill picom || picom -b --experimental-backends"
bindsym --release $mod+Shift+x     exec --no-startup-id "~/.bin/scrotch"
bindsym $mod+Shift+p               exec "mpv /dev/video0"
bindsym $mod+Shift+y               exec --no-startup-id "~/.bin/mpvyt"
bindcode $mod+107                  exec --no-startup-id "~/.bin/podcast"
bindsym --release $mod+Shift+d     exec --no-startup-id "~/.bin/cyclewp"
bindsym --release $mod+Shift+w     exec --no-startup-id "~/.bin/cyclewp -p"
bindsym --release $mod+Mod1+d      exec --no-startup-id "~/.bin/cyclewp -r"
bindsym --release $mod+Mod1+w      exec --no-startup-id "FIND_MAX_DEPTH=1 ~/.bin/cyclewp -r"
bindsym $mod+Control+w             exec --no-startup-id "~/.bin/cyclewp -c"
bindsym $mod+Shift+n exec --no-startup-id "pkill -RTMIN+2 i3blocks"
bindsym $mod+Shift+m exec --no-startup-id "echo 0 >~/.cache/fetchmail.stop; pkill -RTMIN+3 i3blocks"
bindsym $mod+Return                exec "$term"
bindsym $mod+r                     exec "$term -e ranger"
bindsym $mod+Shift+Return          exec "$term $class TerminalFloat"
bindsym $mod+Mod1+j                exec "$term $class TerminalFloat -e julia"
bindsym Control+Mod1+Delete        exec "$term $class CtrlAltDel -e tmux new-session 'htop -t' \; split-window -h gotop \; split-window 'pstree -hU | less -RX'"
bindsym $mod+b                     exec "$BROWSER --no-proxy-server"
bindsym $mod+Shift+b               exec "$BROWSER --no-proxy-server $(xsel -ob)"
bindsym $mod+Control+m             exec --no-startup-id "~/.bin/macho-pdf"
bindsym $mod+q                     exec --no-startup-id "~/.bin/clipqr"
bindsym $mod+Shift+i               exec "xsel -ob | ~/.bin/geturls | ~/.bin/torimg"
bindsym $mod+Control+p             exec --no-startup-id "~/.bin/getpass -i"
</pre>
</details>

<pre>
Logfile URL: https://logs.i3wm.org/logs/6275617628618752.bz2
</pre>

<pre>
- Linux Distribution & Version: Linux x1e2 5.19.8-artix1-1 #1 SMP PREEMPT_DYNAMIC Mon, 12 Sep 2022 08:08:44 +0000 x86_64 GNU/Linux
- Are you using a compositor (e.g., xcompmgr or compton): no, i have it configured and ready to go but it drops my framerate so i keep it off
</pre>

**Comment by Airblader** [comment] 2022-09-23 18:08
Duplicate of https://github.com/i3/i3/issues/5149

**Closed as completed by Airblader** 2022-09-23 18:08 UTC
