### ISSUE TITLE
Switching between tab and tile mode causes thick bar to appear on top of container and eventually cause i3 to crash

### ISSUE THREAD

**Issue by AndreiSva** [Airblader/i3#384] opened 2021-01-23 01:46 UTC
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

Quickly switching between tab and tile mode causes a bar to appear on top of the focused container. Eventually if this is repeated too many times it causes i3 to hang (100% CPU usage) and requires the user to reboot their computer.

## Expected Behavior

i3 should not render a bar when switching tab to tile mode.

## Reproduction Instructions

1. Open a window in tiling mode
2. Press Mod+W to toggle tab mode
3. Press Mod+H to toggle horizontal mode 
4. repeat

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 
Binary i3 version:  4.19 (2020-11-15) © 2009 Michael Stapelberg and contributors
</pre>

<details><summary>Config file</summary><pre>

set $mod Mod4

font pango:monospace 8

exec --no-startup-id nm-applet

set $refresh_i3status killall -SIGUSR1 i3status
bindsym XF86AudioRaiseVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ +10% && $refresh_i3status
bindsym XF86AudioLowerVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ -10% && $refresh_i3status
bindsym XF86AudioMute exec --no-startup-id pactl set-sink-mute @DEFAULT_SINK@ toggle && $refresh_i3status
bindsym XF86AudioMicMute exec --no-startup-id pactl set-source-mute @DEFAULT_SOURCE@ toggle && $refresh_i3status

floating_modifier $mod

bindsym $mod+Return exec i3-sensible-terminal

bindsym $mod+Shift+q kill

bindsym $mod+d exec --no-startup-id rofi -show drun -opacity "40"
bindsym $mod+Tab exec --no-startup-id rofi -show window -opacity "40"

bindsym $mod+j focus left
bindsym $mod+k focus down
bindsym $mod+l focus up
bindsym $mod+semicolon focus right

bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

bindsym $mod+Shift+j move left
bindsym $mod+Shift+k move down
bindsym $mod+Shift+l move up
bindsym $mod+Shift+semicolon move right

bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

bindsym $mod+h split h

bindsym $mod+v split v

bindsym $mod+f fullscreen toggle

bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+e layout toggle split

bindsym $mod+Shift+space floating toggle

bindsym $mod+space focus mode_toggle

bindsym $mod+a focus parent

set $ws1 "1"
set $ws2 "2"
set $ws3 "3"
set $ws4 "4"
set $ws5 "5"
set $ws6 "6"
set $ws7 "7"
set $ws8 "8"
set $ws9 "9"
set $ws10 "10"

bindsym $mod+1 workspace number $ws1
bindsym $mod+2 workspace number $ws2
bindsym $mod+3 workspace number $ws3
bindsym $mod+4 workspace number $ws4
bindsym $mod+5 workspace number $ws5
bindsym $mod+6 workspace number $ws6
bindsym $mod+7 workspace number $ws7
bindsym $mod+8 workspace number $ws8
bindsym $mod+9 workspace number $ws9
bindsym $mod+0 workspace number $ws10

bindsym $mod+Shift+1 move container to workspace number $ws1
bindsym $mod+Shift+2 move container to workspace number $ws2
bindsym $mod+Shift+3 move container to workspace number $ws3
bindsym $mod+Shift+4 move container to workspace number $ws4
bindsym $mod+Shift+5 move container to workspace number $ws5
bindsym $mod+Shift+6 move container to workspace number $ws6
bindsym $mod+Shift+7 move container to workspace number $ws7
bindsym $mod+Shift+8 move container to workspace number $ws8
bindsym $mod+Shift+9 move container to workspace number $ws9
bindsym $mod+Shift+0 move container to workspace number $ws10

bindsym $mod+Shift+c reload
bindsym $mod+Shift+r restart
bindsym $mod+Shift+e exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -B 'Yes, exit i3' 'i3-msg exit'"

mode "resize" {

        bindsym j resize shrink width 10 px or 10 ppt
        bindsym k resize grow height 10 px or 10 ppt
        bindsym l resize shrink height 10 px or 10 ppt
        bindsym semicolon resize grow width 10 px or 10 ppt

        bindsym Left resize shrink width 10 px or 10 ppt
        bindsym Down resize grow height 10 px or 10 ppt
        bindsym Up resize shrink height 10 px or 10 ppt
        bindsym Right resize grow width 10 px or 10 ppt

        bindsym Return mode "default"
        bindsym Escape mode "default"
        bindsym $mod+z mode "default"
}

bindsym $mod+z mode "resize"
smart_borders on

for_window [class=".*"] border pixel 3
gaps inner 7
gaps outer 5
gaps top 5

bindsym $mod+Mod1+Right workspace next
bindsym $mod+Mod1+Left workspace prev

bindsym $mod+p exec ~/.config/rofi/applets/applets/powermenu.sh
bindsym $mod+Shift+s exec ~/.config/rofi/applets/applets/screenshot.sh

exec_always --no-startup-id feh --bg-scale ~/.config/wallpaper
exec_always --no-startup-id picom
exec_always --no-startup-id ~/.config/polybar/launch_bar &
![Screenshot_2021-01-22-14_1919x1079](https://user-images.githubusercontent.com/51296839/105563564-56db4e80-5cd3-11eb-8f03-3efada326d89.png)

</pre>
</details>

<pre>
- Linux Distribution & Version: Arch Linux
- Are you using a compositor (e.g., xcompmgr or compton): Picom
</pre>

## Screenshots

![Screenshot_2021-01-22-35_1920x1080](https://user-images.githubusercontent.com/51296839/105564174-e3870c00-5cd5-11eb-9a4a-d3fc6a1dc513.png)

**Comment by orestisfl** [comment] 2021-01-23 12:58
Duplicate of https://github.com/i3/i3/issues/3001

**Closed as completed by orestisfl** 2021-01-23 12:58 UTC

**Comment by Airblader** [comment] 2021-01-23 13:02
Just to clarify, the misunderstanding here is this:

> Press Mod+H to toggle horizontal mode

That doesn't switch layout mode, it creates a new split container, so you end up nesting a lot of containers into each other. You're looking for Mod+e (default config).
