### ISSUE TITLE
Window title-bars are still rendered when in hidden tab. Visible with transparency.

### ISSUE THREAD

**Issue by sharnoff** [Airblader/i3#337] opened 2020-01-28 17:47 UTC
Thanks for working on this! I picked up i3 a week or so ago and I've been loving it. I noticed this issue a couple days ago, so I decided I'd submit it.

## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
When creating vertical/horizontal splits within tabbed mode, the title bars of "hidden" windows are still visible, even though the contents are not. (See screenshots)

Possibly the same underlying cause as Issue #44.

## Expected Behavior
Unfocused tabs should be completely hidden, except for the system bar at the top displaying which tab is focused in the layout.

## Reproduction Instructions
This layout (or anything similar):

![Screenshot from 2020-01-28 17-43-17](https://user-images.githubusercontent.com/29154784/73290098-beaca580-41f5-11ea-97c7-51d80bbf6c63.png)
![Screenshot from 2020-01-28 17-43-22](https://user-images.githubusercontent.com/29154784/73290106-c0766900-41f5-11ea-9462-15d6c1b777e0.png)

The title bar for one of the inner windows is visible *behind* the transparency, even though the rest of the terminal is not. There are more cases of it in the image (like the top bar) but that's the most visible. It's not specific to this layout, however. I've noticed this bug with any combination that involves multiple windows inside a single tab.

I have intentionally increased the transparency to make this effect more easily visible at a first glance. Something else to note is that the difference in highlighting from windows being focused vs. unfocused is also visible. (See the left vs. right side of the line going across the background)

## Environment
Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.17.1 (2019-08-30) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.17.1 (2019-08-30) (pid 1320)abort…)
Loaded i3 config: /home/max/.config/i3/config (Last modified: Sun 26 Jan 2020 09:28:57 AM GMT, 201245 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

This issue occurs with the default config, running picom (compton).

<pre>
- Linux Distribution & Version: Arch Linux 5.4.15-arch1-1
- Are you using a compositor: Yes, picom (compton).
</pre>

# Final note

If it's not *too* complicated, I'd love to help out with solving this - just let me know whereabouts I should be looking.

**Comment by Airblader** [comment] 2020-12-31 08:20
The root cause here is how i3 draws window decorations, which is on the parent container and not the window itself. I'm tentatively open to fixing this, but if possible I'd prefer fixing this as a performance improvement in upstream i3. The code you're looking for is in `x.c`, and possibly `src/render.c`  

Off the top of my head I'm not sure how easy this is to fix. There also a slim chance this is fixed by https://github.com/i3/i3/pull/4280, though I'd guess that it isn't.

**Comment by AndreiSva** [comment] 2021-01-20 20:09
any update on this?

**Comment by ChaosEternal** [comment] 2021-08-30 07:28
I think this pr maybe helpful here. 
https://github.com/i3/i3/pull/2665

**Comment by Airblader** [comment] 2022-11-06 20:43
I'm closing this issue has i3-gaps is being migrated into i3. If this issue still applies, please reopen it in i3.

**Closed as not planned by Airblader** 2022-11-06 20:43 UTC
