### ISSUE TITLE
Titlebar for all floating windows

### ISSUE THREAD

**Issue by rayanamukami** [Airblader/i3#48] opened 2015-04-14 18:41 UTC
Is there a way to allow floating windows to have a titlebar? I find it useful for moving around dialog windows that pop up at a strange location, or are at the large side. Alternately, can I let all floating windows appear in a corner? Or perhaps, how do you manage this?

I have not found that you can set a for_window to target floating windows and my apologies if here is not the right place to ask this. And of course, thanks for your kind time. ^_^

**Comment by Airblader** [comment] 2015-04-14 18:47
You can use `new_window none` instead of `for_window … border pixel 0`. This will work for windows that are opened floating (note: it does not work for windows that you _make_ floating after they're already open). Which works great for dialogs and the like.

I rarely ever use titlebars, though. To move them around, just hold your modifier and drag with the left mouse button. That way you can click anywhere on the window :)

There's also a `new_float` directive for windows that are opened as floating. You can use that to position such dialogs if you want.

**Comment by Airblader** [comment] 2015-04-14 18:49
By the way, you could also write a script using the IPC which adds borders to windows whenever they are floated and removes them when they are put back into tiling mode. You'll just have to write it yourself, I never needed it, so I didn't write it.

**Comment by Airblader** [comment] 2015-04-14 18:50
I'm closing this issue since it's not an issue. Please feel free to continue this conversation even if the issue is closed.

**Closed as completed by Airblader** 2015-04-14 18:50 UTC

**Comment by rayanamukami** [comment] 2015-04-14 19:18
Thanks for the fast answer and your suggestion works well. ^_^
I wonder where I should ask these non-issue questions?

Apart from the scratchpad window, I don't often make windows floating. But "bindsym Mod1+f floating toggle, border toggle" work a bit clumsily, since there are three modes for "border toggle" (normal, none, 1pixel) and I'm not sure if there's a way to define the toggle modes?

**Comment by Airblader** [comment] 2015-04-14 19:21
> I wonder where I should ask these non-issue questions?

Asking them here is fine if they relate to my fork. If they are general questions about i3, you should ask them on faq.i3wm.org.

> I'm not sure if there's a way to define the toggle modes?

There isn't. As I said, you'll probably have to write a script that subscribes to IPC events for this. Should be fairly straightforward, though.

**Comment by rayanamukami** [comment] 2015-04-14 19:27
Hehe, okay, I'll read and give it a try. ^_^

**Comment by rayanamukami** [comment] 2015-04-14 22:57
I stop here since I need more time to find and understand everything. Sorry for my inability to provide anything functional.

In case a future person, perhaps as ignorant as I, wishes to write it, then here is for reference an attempt based on the documentation and examples found on http://i3wm.org/docs/ipc.html and https://github.com/acrisci/i3ipc-python.

```
import i3ipc

i3 = i3ipc.Connection()

tree = i3.get_tree()

def border_on_floating(i3, e):
    for user_on in tree:
        e.window.command('border normal')
    for user_off in tree:
        e.window.command('border pixel 3')

i3.on('window::floating', border_on_floating)

i3.main()
```

**Comment by Naatan** [comment] 2016-06-13 16:20
Here's a working version for the latest version of i3:

```
#!/usr/bin/env python3

import i3ipc

i3 = i3ipc.Connection()

def on_window_open(i3, e):
    ws = i3.get_tree().find_focused().workspace()
    e.container.command('border normal')

i3.on('window::floating', on_window_open)

i3.main()
```

**Comment by BenSYZ** [comment] 2021-08-16 10:53
Based on  @Naatan @rayanamukami

```python
#!/usr/bin/env python3

import i3ipc

i3 = i3ipc.Connection()

def border_on_floating(i3, e):
    ws = i3.get_tree().find_focused().workspace()
    if (e.container.floating=='user_off'):
        e.container.command('border none')
    elif (e.container.floating=='user_on'):
        e.container.command('border normal')

i3.on('window::floating', border_on_floating)

i3.main()
```
