### ISSUE TITLE
Error while loading libxcb-xrm

### ISSUE THREAD

**Issue by thepaperpilot** [Airblader/i3#93] opened 2016-06-22 23:45 UTC
Running i3 outputs the following error:

```
i3: error while loading shared libraries: libxcb-xrm.so.0: cannot open shared object file: No such file or directory
```

There is no version output for `i3 --version` because it just outputs the same error. I compiled from source earlier today. 

I tried installing libxcb-xrm-dev, but it's apparently only on 16.10 I am running Ubuntu 16.04, which is a LTS release.

**Comment by Airblader** [comment] 2016-06-23 04:45
I don't really know how you compiled it without the library, but this is a duplicate of #88 and #89. I suggest someone creates a PPA or gets someone to create a PPA, but it seems like nobody ever listens to these suggestions once they figured out how to compile the library from source.

**Closed as completed by Airblader** 2016-06-23 04:45 UTC

**Comment by thepaperpilot** [comment] 2016-06-23 04:48
I compiled xcb-util-xrm before compiling i3-gaps, this error came after trying to run it.

**Comment by Airblader** [comment] 2016-06-23 04:50
In that case it sounds like you installed the library into some folder not included in the path the linker looks. I'd suggest removing it again and installing it again with the directory prefix set the same way similar packages (like xcb-util-cursor) are built on Ubuntu. Again, if someone did this in a PPA, people wouldn't have to start from scratch everytime.

**Comment by thepaperpilot** [comment] 2016-06-23 04:55
A reinstall worked, thank you!

**Comment by lukovdm** [comment] 2016-07-23 18:46
Hi,

I would love to make an ppa, but I have a broken system, so how do you set the directory prefix and  where to. I couldn't find it with your instructions.

**Comment by Airblader** [comment] 2016-07-24 04:05
The library exists as a package in Debian testing. Just port that to the PPA.

**Comment by waplet** [comment] 2016-09-07 19:33
`sudo ./autogen.sh --prefix=/usr` in Ubuntu 15.10 LTS
after that `sudo make install` will install in correct dir and

```
λ ~/apps/xcb-util-xrm/ master i3 -v
i3 version 4.12-126-g1d4b619 (2016-08-30, branch "gaps-next") © 2009 Michael Stapelberg and contributors
```
