### ISSUE TITLE
After a new release, some apps show titlebars when they shouldn't

### ISSUE THREAD

**Issue by Volian0** [Airblader/i3#451] opened 2022-09-22 10:46 UTC
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

I just upgraded i3-gaps on my Arch Linux system and some programs (like Alacritty) now show titlebar which I don't want.
I'm using "default_border pixel 1" in my config so they shouldn't show a titlebar.
## Expected Behavior

Windows shouldn't have a titlebar, just like before the update.
## Reproduction Instructions

Put "default_border pixel 1" in the config, and launch Alacritty/Discord/Chromium or some other app
## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.21 (2022-09-21) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.21 (2022-09-21) (pid 9178)
Loaded i3 config:
  /home/volian/.config/i3/config (main) (last modified: czw, 22 wrz 2022, 12:39:13, 71 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

<details><summary>Config file</summary><pre>
https://pastebin.com/PPPwgY75
</pre>
</details>

<pre>
- Linux Distribution & Version: Arch Linux 5.19.10-zen1-1-zen
- Are you using a compositor (e.g., xcompmgr or compton): no
</pre>

**Comment by Airblader** [comment] 2022-09-22 10:47
I'll close this as a likely duplicate of https://github.com/i3/i3/issues/5149.

**Closed as completed by Airblader** 2022-09-22 10:47 UTC
